#!/bin/bash
# This script modifies the jitsi-meet.cfg.lua to add our custom modules to the MUC component

CONFIG_FILE="/config/conf.d/jitsi-meet.cfg.lua"

# Wait for the config file to be generated by the Jitsi entrypoint
while [ ! -f "$CONFIG_FILE" ]; do
    sleep 1
done

# Check if our modules are already in the config
if grep -q "jitsi_webhooks_enhanced" "$CONFIG_FILE"; then
    echo "Custom modules already configured"
    exit 0
fi

# Add our custom modules to the MUC component modules_enabled list
sed -i '/Component "muc.meet.jitsi" "muc"/,/modules_enabled = {/!b; /modules_enabled = {/a\        "jitsi_webhooks_enhanced";\n        "room_access_validator";' "$CONFIG_FILE"

echo "Custom modules added to MUC component configuration"
